inertial_params:
    mass:
        m: 2.0
    MOI:
        Jxx: 0.020
        Jxy: 0
        Jxz: 0
        Jyy: 0.020
        Jyz: 0
        Jzz: 0.012
    CM:
        x: 0.00
        y: 0.000
        z: -0.02
aero_coeffs:
    C_T: 1.48e-9
    C_M: 2.524e-9
    l: 0.340